[app]
build_directory = "./"
sdk = "C"
devices = ["nanox", "nanos+", "stax", "flex", "apex_p"]

[use_cases]
use_test_keys = "TEST_PUBLIC_KEY=1 TRUSTED_NAME_TEST_KEY=1"
dbg_use_test_keys = "DEBUG=1 TEST_PUBLIC_KEY=1 TRUSTED_NAME_TEST_KEY=1"
full_replay = "DEBUG=1 TESTING=1 TEST_PUBLIC_KEY=1 TRUSTED_NAME_TEST_KEY=1 FIXED_TLV_CHALLENGE=1"
dbg_full_replay = "DEBUG=1 TESTING=1 TEST_PUBLIC_KEY=1 TRUSTED_NAME_TEST_KEY=1 FIXED_TLV_CHALLENGE=1"
dbg_no_check = "DEBUG=1 BYPASS_TRANSACTION_ID_CHECK=1 BYPASS_CHECK_ADDRESS=1 BYPASS_CHECK_PARTNER=1 BYPASS_CHECK_COIN_CFG=1"

[tests]
pytest_directory = "./test/python/"
