# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18src/proto/protocol.proto\x12\x0bledger_swap\"\xe6\x02\n\x16NewTransactionResponse\x12\x15\n\rpayin_address\x18\x01 \x01(\t\x12\x16\n\x0epayin_extra_id\x18\x02 \x01(\t\x12\x18\n\x10payin_extra_data\x18\r \x01(\x0c\x12\x16\n\x0erefund_address\x18\x03 \x01(\t\x12\x17\n\x0frefund_extra_id\x18\x04 \x01(\t\x12\x16\n\x0epayout_address\x18\x05 \x01(\t\x12\x17\n\x0fpayout_extra_id\x18\x06 \x01(\t\x12\x15\n\rcurrency_from\x18\x07 \x01(\t\x12\x13\n\x0b\x63urrency_to\x18\x08 \x01(\t\x12\x1a\n\x12\x61mount_to_provider\x18\t \x01(\x0c\x12\x18\n\x10\x61mount_to_wallet\x18\n \x01(\x0c\x12\x1d\n\x15\x64\x65vice_transaction_id\x18\x0b \x01(\t\x12 \n\x18\x64\x65vice_transaction_id_ng\x18\x0c \x01(\x0c\"1\n\x08UDecimal\x12\x13\n\x0b\x63oefficient\x18\x01 \x01(\x0c\x12\x10\n\x08\x65xponent\x18\x02 \x01(\r\"\xd8\x01\n\x0fNewSellResponse\x12\x14\n\x0ctrader_email\x18\x01 \x01(\t\x12\x13\n\x0bin_currency\x18\x02 \x01(\t\x12\x11\n\tin_amount\x18\x03 \x01(\x0c\x12\x12\n\nin_address\x18\x04 \x01(\t\x12\x13\n\x0bin_extra_id\x18\x08 \x01(\t\x12\x14\n\x0cout_currency\x18\x05 \x01(\t\x12)\n\nout_amount\x18\x06 \x01(\x0b\x32\x15.ledger_swap.UDecimal\x12\x1d\n\x15\x64\x65vice_transaction_id\x18\x07 \x01(\x0c\"\xa8\x01\n\x0fNewFundResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x02 \x01(\t\x12\x13\n\x0bin_currency\x18\x03 \x01(\t\x12\x11\n\tin_amount\x18\x04 \x01(\x0c\x12\x12\n\nin_address\x18\x05 \x01(\t\x12\x13\n\x0bin_extra_id\x18\x07 \x01(\t\x12\x1d\n\x15\x64\x65vice_transaction_id\x18\x06 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.protocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWTRANSACTIONRESPONSE._serialized_start=42
  _NEWTRANSACTIONRESPONSE._serialized_end=400
  _UDECIMAL._serialized_start=402
  _UDECIMAL._serialized_end=451
  _NEWSELLRESPONSE._serialized_start=454
  _NEWSELLRESPONSE._serialized_end=670
  _NEWFUNDRESPONSE._serialized_start=673
  _NEWFUNDRESPONSE._serialized_end=841
# @@protoc_insertion_point(module_scope)
