# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exchange.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x65xchange.proto\"\xaa\x02\n\x16NewTransactionResponse\x12\x15\n\rpayin_address\x18\x01 \x02(\t\x12\x16\n\x0epayin_extra_id\x18\x02 \x02(\t\x12\x16\n\x0erefund_address\x18\x03 \x02(\t\x12\x17\n\x0frefund_extra_id\x18\x04 \x02(\t\x12\x16\n\x0epayout_address\x18\x05 \x02(\t\x12\x17\n\x0fpayout_extra_id\x18\x06 \x02(\t\x12\x15\n\rcurrency_from\x18\x07 \x02(\t\x12\x13\n\x0b\x63urrency_to\x18\x08 \x02(\t\x12\x1a\n\x12\x61mount_to_provider\x18\t \x02(\x0c\x12\x18\n\x10\x61mount_to_wallet\x18\n \x02(\x0c\x12\x1d\n\x15\x64\x65vice_transaction_id\x18\x0b \x02(\t\"1\n\x08UDecimal\x12\x13\n\x0b\x63oefficient\x18\x01 \x02(\x0c\x12\x10\n\x08\x65xponent\x18\x02 \x02(\r\"\xb7\x01\n\x0fNewSellResponse\x12\x14\n\x0ctrader_email\x18\x01 \x02(\t\x12\x13\n\x0bin_currency\x18\x02 \x02(\t\x12\x11\n\tin_amount\x18\x03 \x02(\x0c\x12\x12\n\nin_address\x18\x04 \x02(\t\x12\x14\n\x0cout_currency\x18\x05 \x02(\t\x12\x1d\n\nout_amount\x18\x06 \x02(\x0b\x32\t.UDecimal\x12\x1d\n\x15\x64\x65vice_transaction_id\x18\x07 \x02(\x0c\"\x93\x01\n\x0fNewFundResponse\x12\x0f\n\x07user_id\x18\x01 \x02(\t\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x02 \x02(\t\x12\x13\n\x0bin_currency\x18\x03 \x02(\t\x12\x11\n\tin_amount\x18\x04 \x02(\x0c\x12\x12\n\nin_address\x18\x05 \x02(\t\x12\x1d\n\x15\x64\x65vice_transaction_id\x18\x06 \x02(\x0c')
)




_NEWTRANSACTIONRESPONSE = _descriptor.Descriptor(
  name='NewTransactionResponse',
  full_name='NewTransactionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payin_address', full_name='NewTransactionResponse.payin_address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payin_extra_id', full_name='NewTransactionResponse.payin_extra_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refund_address', full_name='NewTransactionResponse.refund_address', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='refund_extra_id', full_name='NewTransactionResponse.refund_extra_id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payout_address', full_name='NewTransactionResponse.payout_address', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payout_extra_id', full_name='NewTransactionResponse.payout_extra_id', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency_from', full_name='NewTransactionResponse.currency_from', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency_to', full_name='NewTransactionResponse.currency_to', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount_to_provider', full_name='NewTransactionResponse.amount_to_provider', index=8,
      number=9, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount_to_wallet', full_name='NewTransactionResponse.amount_to_wallet', index=9,
      number=10, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_transaction_id', full_name='NewTransactionResponse.device_transaction_id', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=317,
)


_UDECIMAL = _descriptor.Descriptor(
  name='UDecimal',
  full_name='UDecimal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coefficient', full_name='UDecimal.coefficient', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exponent', full_name='UDecimal.exponent', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=368,
)


_NEWSELLRESPONSE = _descriptor.Descriptor(
  name='NewSellResponse',
  full_name='NewSellResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trader_email', full_name='NewSellResponse.trader_email', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_currency', full_name='NewSellResponse.in_currency', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_amount', full_name='NewSellResponse.in_amount', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_address', full_name='NewSellResponse.in_address', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='out_currency', full_name='NewSellResponse.out_currency', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='out_amount', full_name='NewSellResponse.out_amount', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_transaction_id', full_name='NewSellResponse.device_transaction_id', index=6,
      number=7, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=554,
)


_NEWFUNDRESPONSE = _descriptor.Descriptor(
  name='NewFundResponse',
  full_name='NewFundResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='NewFundResponse.user_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_name', full_name='NewFundResponse.account_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_currency', full_name='NewFundResponse.in_currency', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_amount', full_name='NewFundResponse.in_amount', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_address', full_name='NewFundResponse.in_address', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_transaction_id', full_name='NewFundResponse.device_transaction_id', index=5,
      number=6, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=704,
)

_NEWSELLRESPONSE.fields_by_name['out_amount'].message_type = _UDECIMAL
DESCRIPTOR.message_types_by_name['NewTransactionResponse'] = _NEWTRANSACTIONRESPONSE
DESCRIPTOR.message_types_by_name['UDecimal'] = _UDECIMAL
DESCRIPTOR.message_types_by_name['NewSellResponse'] = _NEWSELLRESPONSE
DESCRIPTOR.message_types_by_name['NewFundResponse'] = _NEWFUNDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewTransactionResponse = _reflection.GeneratedProtocolMessageType('NewTransactionResponse', (_message.Message,), dict(
  DESCRIPTOR = _NEWTRANSACTIONRESPONSE,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:NewTransactionResponse)
  ))
_sym_db.RegisterMessage(NewTransactionResponse)

UDecimal = _reflection.GeneratedProtocolMessageType('UDecimal', (_message.Message,), dict(
  DESCRIPTOR = _UDECIMAL,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:UDecimal)
  ))
_sym_db.RegisterMessage(UDecimal)

NewSellResponse = _reflection.GeneratedProtocolMessageType('NewSellResponse', (_message.Message,), dict(
  DESCRIPTOR = _NEWSELLRESPONSE,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:NewSellResponse)
  ))
_sym_db.RegisterMessage(NewSellResponse)

NewFundResponse = _reflection.GeneratedProtocolMessageType('NewFundResponse', (_message.Message,), dict(
  DESCRIPTOR = _NEWFUNDRESPONSE,
  __module__ = 'exchange_pb2'
  # @@protoc_insertion_point(class_scope:NewFundResponse)
  ))
_sym_db.RegisterMessage(NewFundResponse)


# @@protoc_insertion_point(module_scope)
