/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Tue Nov 26 11:35:27 2019. */

#include "protocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ledger_swap_NewTransactionResponse_fields[12] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, ledger_swap_NewTransactionResponse, payin_address, payin_address, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, ledger_swap_NewTransactionResponse, payin_extra_id, payin_address, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, ledger_swap_NewTransactionResponse, refund_address, payin_extra_id, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, ledger_swap_NewTransactionResponse, refund_extra_id, refund_address, 0),
    PB_FIELD(  5, STRING  , SINGULAR, CALLBACK, OTHER, ledger_swap_NewTransactionResponse, payout_address, refund_extra_id, 0),
    PB_FIELD(  6, STRING  , SINGULAR, CALLBACK, OTHER, ledger_swap_NewTransactionResponse, payout_extra_id, payout_address, 0),
    PB_FIELD(  7, STRING  , SINGULAR, CALLBACK, OTHER, ledger_swap_NewTransactionResponse, currency_from, payout_extra_id, 0),
    PB_FIELD(  8, STRING  , SINGULAR, CALLBACK, OTHER, ledger_swap_NewTransactionResponse, currency_to, currency_from, 0),
    PB_FIELD(  9, BYTES   , SINGULAR, STATIC  , OTHER, ledger_swap_NewTransactionResponse, amount_to_provider, currency_to, 0),
    PB_FIELD( 10, BYTES   , SINGULAR, STATIC  , OTHER, ledger_swap_NewTransactionResponse, amount_to_wallet, amount_to_provider, 0),
    PB_FIELD( 11, STRING  , SINGULAR, CALLBACK, OTHER, ledger_swap_NewTransactionResponse, device_transaction_id, amount_to_wallet, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
