#pragma once

typedef enum {
    INITIAL_STATE,
    WAITING_TRANSACTION,
    PROVIDER_SET,
    PROVIDER_CHECKED,
    TRANSACTION_RECEIVED,
    SIGNATURE_CHECKED,
    PAYOUT_ADDRESS_CHECKED,
    ALL_ADDRESSES_CHECKED,
    WAITING_USER_VALIDATION,
    WAITING_SIGNING,
    SIGN_FINISHED,
    STATE_UPPER_BOUND,
} state_e;
