name: Code style check

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - develop
  pull_request:

jobs:
  check_linting:
    name: Check linting using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_lint.yml@debian
    with:
      source: './src'
      extensions: 'h,c'
      version: 12
