---
name: Python client checks, package build and deployment

on:
  workflow_dispatch:
  push:
    tags:
      - 'client-*'
    branches:
      - develop
      - master
    paths:
      - client/**
      - .github/workflows/python-client.yml
  pull_request:
    paths:
      - client/**
      - .github/workflows/python-client.yml

jobs:
  package_and_deploy:
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_pypi_deployment.yml@v1
    with:
      package_name: 'ledger_app_clients.exchange'
      package_directory: 'client'
      publish: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/client-') }}
      jfrog_deployment: false
    secrets:
      pypi_token: ${{ secrets.PYPI_PUBLIC_API_TOKEN }}
