---
name: Regenerate and commit snapshots

on:
  workflow_dispatch:

jobs:
  delete_snapshots:
    name: Delete current snapshots
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete snapshots
        run: |
          rm -rf ./test/python/snapshots

  regenerate_snapshots:
    name: Run ragger with golden run
    needs: delete_snapshots
    uses: ./.github/workflows/reusable_swap_functional_tests.yml
    with:
      branch_for_exchange: ${{ github.ref }}
      regenerate_snapshots: true
